### ISSUE TITLE
Incorrect height when saving as gif

### ISSUE THREAD

**Issue by fionnbharra** [zverok/worldize#3]
When saving the map as a gif the height is incorrect. There is a large space below the bottom of the map. 

```
# saving as png works as expected
worldize = Worldize::Countries.new
img = worldize.draw
img.write('blank.png') #image is 1024x175, as expected
```

```
# saving as gif does not
worldize = Worldize::Countries.new
img = worldize.draw
img.write('blank.gif') #image is 1024x1024, with a large transparent space below the map
```

[Example here](http://imgur.com/ROmERYq)

Great gem btw, really nice to use.

**Comment by zverok** [comment]
Thank you! 
Forgot completely about some RMagick quirks :(
Fixed this in master branch.

**Comment by fionnbharra** [comment]
Awesome, thanks
