### ISSUE TITLE
undefined method 'using'

### ISSUE THREAD

**Issue by ciryon** [zverok/worldize#4]
I'm having problems getting worldize to work. I get the following error both when running the worldize executable and when including it in my Ruby on Rails application:

```
$ worldize
WARN: Unresolved specs during Gem::Specification.reset:
      hashie (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/Library/Ruby/Gems/2.0.0/gems/worldize-0.0.1/lib/worldize/refinements.rb:3: warning: Refinements are experimental, and the behavior may change in future versions of Ruby!
/Library/Ruby/Gems/2.0.0/gems/worldize-0.0.1/lib/worldize/web_mercator.rb:7:in '<module:WebMercator>': undefined method 'using' for Worldize::WebMercator:Module (NoMethodError)
    from /Library/Ruby/Gems/2.0.0/gems/worldize-0.0.1/lib/worldize/web_mercator.rb:6:in '<module:Worldize>'
    from /Library/Ruby/Gems/2.0.0/gems/worldize-0.0.1/lib/worldize/web_mercator.rb:5:in '<top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/worldize-0.0.1/lib/worldize.rb:8:in 'require_relative'
    from /Library/Ruby/Gems/2.0.0/gems/worldize-0.0.1/lib/worldize.rb:8:in '<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:127:in 'require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:127:in 'rescue in require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:40:in 'require'
    from /Library/Ruby/Gems/2.0.0/gems/worldize-0.0.1/bin/worldize:3:in '<top (required)>'
    from /usr/local/bin/worldize:22:in 'load'
    from /usr/local/bin/worldize:22:in '<main>'
```

I have made sure that 'hashie' is installed as well. 

My Ruby version is `ruby 2.0.0p648`

Any idea what's wrong?

**Comment by zverok** [comment]
I assume it's something with [refinements](http://ruby-doc.org/core-2.1.1/doc/syntax/refinements_rdoc.html).

`using` is a way of including refined methods in code. 

Docs of [ruby-2.0.0](http://ruby-doc.org/core-2.0.0/doc/syntax/refinements_rdoc.html) seem to list the same syntax, but `using` keyword worked only in top-level context then, not inside modules.

As support of Ruby 2.0.0 already [have ended](https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/), the only thing I can recommend is update your Ruby version :(
