### ISSUE TITLE
gem not working in ubuntu

### ISSUE THREAD

**Issue by xekhz** [zverok/worldize#5]
hello im trying to build a map using your worldize, that seems to be very good, but it is not working in ubuntu
I have the following
**Operating System**
Description:    Ubuntu 14.04.3 LTS
Release:    14.04
Codename:   trusty
**RUBY**
ruby 1.9.3p484 (2013-11-22 revision 43786) [i686-linux]

**CODE SNIPPET:**
require 'worldize'
worldize = Worldize::Countries.new
img = worldize.draw # Magick::Image of RMagick
img.write('/tmp/blank.png')

**I GET THE FOLLOWING ERRORS:**
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `require': /var/lib/gems/1.9.1/gems/worldize-0.0.1/lib/worldize.rb:73: syntax error, unexpected tPOW (SyntaxError)
    def draw_highlighted(*countries, **options)
                                       ^
/var/lib/gems/1.9.1/gems/worldize-0.0.1/lib/worldize.rb:79: syntax error, unexpected tPOW
... to_color, value_by_country, **options)
...                               ^
/var/lib/gems/1.9.1/gems/worldize-0.0.1/lib/worldize.rb:121: syntax error, unexpected keyword_end, expecting $end
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in`rescue in require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
    from log_analyzer.rb:109:in`<main>'

How can i use worldize.. thanks for the help

**Comment by zverok** [comment]
It should be described in README, but Worldize works only on moder Rubies. Modern is > 2.0, where refinements work and hash argument work.

JFYI, support for Ruby 1.9.3 have [been ended](https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/) already, as well as [for Ruby 2.0](https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/).

I will never have my target in supporting discontinued versions of Ruby.

**Comment by xekhz** [comment]
thanks for the quick reply... will try modern rubies.
